#!/bin/bash
#
# make-dcb :: simple script to convert text to DCB directives
#
# Reads stdin, outputs DCB statements compatible with 
# the 6502js emulator at https://github.com/ctyler/6502js/
#
# Chris Tyler 2020-02-03 - Licensed under GPLv2+

sed -e "s/$/\n/g" -e 's/\(.\)/"\1",/g' -e 's/" "/32/g' -e 's/"\n"/$0d/g'|sed 's/\([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,\)/\n\1/g'|grep .|sed -e 's/^/dcb /' -e 's/,$//'
echo "dcb 00"

